### ISSUE TITLE
Demo link is broken

### ISSUE THREAD

**Issue by harley** [GAKUEngine/gaku#343]
On both the website and README file, the demo link is http://demo.gakuengine.com/ but it's a 404 right now.

**Comment by Kagetsuki** [comment]
We're aware. We've been significantly impeded as our sponsor dropped out - so we've had to spend a lot of time on other projects before we can focus again on GAKU. Unless we can find someone who wants to fund or partner with us on the project it may be a while before we can really focus on it again. In the mean time the demo was taking too much time to reset and keep running. We're planning on at least updating the site and putting up a new auto-resetting demo in the next few months.

If you're interested in GAKU Engine the base is actually pretty stable, but it's still alpha level. I'd say we're going to need a good 200k$ and about a year to really get it to what I would call a regularly usable level. If you our anyone you know would be interested in partnering up we're absolutely listening.
